### ISSUE TITLE
Failed To register the client

### ISSUE THREAD

**Issue by kamarshad** [MobileFirst-Platform-Developer-Center/AdapterBasedAuthObjC#1]
Hi @nasht00 @chethankumar @IdanAdar @ajaychebbi 

My iOS app is based on **IBMMobileFirstPlatformFoundation** and the current version is V 7.1
I am facing a weird issue every time whenever my iOS application (with fresh installed) is trying to communicate with the IBM MobileFirst Platform Server is getting failed and received the weird response having below error message.

**Error Message: Request to REQUEST_URL failed. Failed To register the client.**

Can someone please help why this error is being occurred.
Thanks in advance

**Comment by sriniketana** [comment]
@kamarshad Are you using this sample ? If not, share your code snippet. Also, provide the steps that you followed

**Comment by kamarshad** [comment]
Sorry for late reply. My question was related to **IBMMobileFirstPlatformFoundation** and I had got the reason why I was getting that error.

Thank you very much for your kind reply.
